### ISSUE TITLE
Every time the constructor is called, an HTTP request is sent to Loki asking it for it's version

### ISSUE THREAD

**Issue by simskij** [canonical/loki-k8s-operator#112]
### Bug Description

Every time the constructor is called, an HTTP request is sent to Loki asking it for its version. This information is then logged into the debug logs, spamming them with unneeded log lines.

### To Reproduce

1. juju deploy loki-k8s --channel edge
2. look in the debug logs

### Environment

charm version: latest/edge

### Relevant log output

```shell
N/A
```

**Comment by balbirthomas** [comment]
The `_provide_loki()` method  queries the Loki server version using a HTTP API call and raise different types of exceptions depending on the success or failure of this call. This method is only being used to set a status message by the Loki provider charm depending on if the Loki server is active and reachable or not. The docstring of the `LokiPushApiProvider` object also recommends the use of such a `_provide_loki()` method in this manner. However neither the docstring nor the Loki charm use the exceptions raised by the `_provide_loki()` to conditionally instantiate the `LokiPushApiProvider` object only if the Loki server is active and reachable. The `LokiPushApiProvier` object does use the Loki HTTP API in its `_check_alert_rules` method. This method is invoked in response to any changes in the relation with the consumer object and in response to a pebble ready method (see [PR 132](https://github.com/canonical/loki-k8s-operator/pull/132) ). Hence instantiating the `LokiPushApiProvider` object can lead to false negative result in `_check_alert_rules` just because the Loki HTTP API is not responsive. In view of these observations it is proposed that

1. The `_provide_loki()` method be renamed to something like `_is_loki_active()`. Instead of raising exceptions this method may return a boolean that asserts if the Loki server HTTP API is responsive or not.
2. Instantiation of the `LokiPushApiProvider` be guarded by check for `_is_loki_active()`.

There may be a few concerns here. For example how should such a scenario be handled

- The Loki charm receives a relation changed event but its workload container is not yet alive so this event is ignored (as per [PR 132](https://github.com/canonical/loki-k8s-operator/pull/132) ).
- Subsequently on pebble ready the Loki charm fails to see an active loki server because of the time lag between the workload container becoming active and the time it takes a Loki HTTP API to become responsive. hence the Loki charm does not instantiate the `LokiPushApiProvider` . Hence the pending relation changed event is still not handled. In fact it will never be handled.

What is missing here is the functionality of a "Readyness Probe" and the Loki charm being informed through a suitable event when the status of such a readyness probe changes. In the absence of such functionality one approach to solving the problem is to use the periodic `update-status` event to check for active status of Loki server (i.e. responsiveness of its HTTP API) and update all related consumers.

**Comment by Abuelodelanada** [comment]
I think renaming the method and guarding the instantiation of `LokiPushApiProvider` is a good idea.
Let's keep in mind that we will need to observe the `on.loki_push_api_alert_rules_changed` event inside the guard, for instance:

```python
if self._is_loki_active():
    self.loki_provider = LokiPushApiProvider(
            self,
            address=external_url.hostname or "",
            port=external_url.port or self._port,
            scheme=external_url.scheme,
            path=f"{external_url.path}/loki/api/v1/push",
     )
    self.framework.observe(self.loki_provider.on.loki_push_api_alert_rules_changed, self._loki_push_api_alert_rules_changed)
```

**Comment by rbarry82** [comment]
> I think renaming the method and guarding the instantiation of `LokiPushApiProvider` is a good idea. Let's keep in mind that we will need to observe the `on.loki_push_api_alert_rules_changed` event inside the guard, for instance:
> 
> ```python
> if self._is_loki_active():
>     self.loki_provider = LokiPushApiProvider(
>             self,
>             address=external_url.hostname or "",
>             port=external_url.port or self._port,
>             scheme=external_url.scheme,
>             path=f"{external_url.path}/loki/api/v1/push",
>      )
>     self.framework.observe(self.loki_provider.on.loki_push_api_alert_rules_changed, self._loki_push_api_alert_rules_changed)
> ```

As mentioned earlier, we have to be very, very careful with this.

The actual Loki charm does not listen to `relation_*` events, but they will still be emitted as it is part of the relation. If there are no observers, they will simply disappear.

In the case of, say, a bundle deployment, where a `relation-joined` event may occur before Loki is actually ready, this means that `relation-joined` simply disappears into the ether, never to be seen again. Any data which is expected to be set in `relation_joined` will not be.

The alternative to this is quite literally the "common exit hook" which we have a number of issue about moving away from. If the charm/library looks at every relation data bag on every event to compare the state of the charm, we should probably try to hash absolutely everything.

In order to protect the validity of `relation-*` events in this case, I'd suggest waiting until after container operations are moved into the charm itself, so the provider can manage relation data only.

**Comment by mmanciop** [comment]
I honestly do not see why we need to have Loki active in order to create the rules in the container. For that, we need only Pebble.

I am also very conflicted about providing the URL via `LokiPushApiProvider` ONLY if Loki is active, as relation changes have a lag to propagate to the other side. Interestingly enough, if Loki is _not_ active, we do NOT remove the URL from `LokiPushApiProvider`, which is at very least least inconsistent.

**Comment by balbirthomas** [comment]
> Interestingly enough, if Loki is _not_ active, we do NOT remove the URL from `LokiPushApiProvider`, which is at very least least inconsistent.

How can a Provider charm let the Consumer know that its workload endpoint is temporarily not in service (due to say upgrade or maintenance etc) ? This is to prevent errors in the Consumer charm should it try to connect to the workload endpoints of the Provider charm during this process. There was previously an attempt to cater to this issue using `ready()` and `unready()` methods in the Operator Framework through an relation management object that was removed as it was not being used as intended.

**Comment by balbirthomas** [comment]
Closed PR https://github.com/canonical/loki-k8s-operator/pull/135 since fix is moved to https://github.com/canonical/loki-k8s-operator/pull/151
