### ISSUE TITLE
Explicitly document need to ensure logs are topology labeled

### ISSUE THREAD

**Issue by balbirthomas** [canonical/loki-k8s-operator#118]
### Bug Description

When a relation is added between `LokiPushApiProvider` and `LokiPushApiConsumer` the provider sends the Loki push API endpoint URL to the consumer. Hence the consumer can forward logs directly to this endpoint. However if the consumer chooses to do so using a custom client rather than the provided `promtail` resource then Juju topology labels are not automatically injected into the logs and the consumer needs to add topology labels to each log explicitly. 

At present the Loki documentation does not make this explicit. This is a gotcha that needs to be made explicit and prominent in the docs. Perhaps it will be good to have an example on how to generate the Juju topology labels also.

### To Reproduce

NA

### Environment

NA

### Relevant log output

```shell
NA
```

**Comment by rbarry82** [comment]
It is always possible for logs to be pushed directly to Loki, though, regardless of the relation. The k8s service can be looked up, among other means.

Considering the renaming of cross-model-relations and the intrinsic guards around permissions and privacy from outside any given model, it's unlikely that any sort of reverse mapping from "IP address -> topology" exists, not least of which because overlapping CIDRs in different clusters or substrates which are only externally visible through some DNAT/SNAT means that "10.10.10.1" may not be unique in any way, nor externally resolvable.

Do we really think we need to document "hey, our Loki charm is still Loki"? I mean this as a serious question. The documentation is intended for using as part of the charm ecosystem, and usage above and beyond that is pretty much "go read the upstream docs". We could certainly point there.

It's worth noting that `cos-configuration` similarly has no meaningful way to map dashboards/alerts back to automatically labeled metrics/logs/traces or any other telemetry. Writing alert rules/dashboards which can still target data with sufficient cardinality even in the absence of Juju Topology (since "contributed" alerts from `cos-config` cannot know what the topology of any given outside Cassandra will be, for example), and if we're documenting it there as a "how-to", we can/should point there instead.

This comes back to my earlier suggestion for using `cos-configuration` in the integration tests rather than keeping a second tester charm which only has "bad" rules. It is not useful in that sense, but using a lookaside repo for specific positive/negative integration testing could serve as "living documentation/reference" for "here is how you can use these without the safety net relations+topology gives you"

**Comment by balbirthomas** [comment]
Just trying to clarify, are you suggesting that  

1. We must *not* advice Loki charm users that by pushing "logs directly to loki" they will loose the "continuity of logs" that Juju Topology provides ? 
2. Is it OK if we advice client charm authors how they may construct and use Juju Topology in their charms should they choose to send logs directly to Loki using `LokiPushApiConsumer` since Topology is not automatically injected in this case ?

**Comment by rbarry82** [comment]
1. I would expect them to already know this, and whatever method they use for "continuity of logs" could be specified via whatever labels/transformations they provide themselves. The continuity of logs topology provides is only important insofar as "observability labels from charmed applications using JujuTopology are coherent across applications". That is not orthogonal to `job=foo`, which can be equally continuous. From my POV, this would be more or less the same sort of warning as "directly performing operations on a database will lose the continuity/coherency an ORM provides". By writing directly to Loki, they are removing a middleware we add, which is not critical (or possibly even desirable) for the operation of Loki. For users who simply want to use the Loki charm outside of COS as a sink for the fluent bit, rsyslog from a bunch of physical machines, or other, this is the de-facto use case for Loki anyway.
2. Of course. Though that, from my POV, highlights the fact that `LokiPushApiConsumer` does not actually provide any mechanism of interacting with Loki other than an endpoint address. Implementation is up to the author. I would think that we would do well to document an example construction of `python-logging-loki` using `LokiPushApiConsumer` (`LogProxyConsumer` _does_ add labels), using `LokiPushApiConsumer.topology` as part of the `tags` field, which may tell users who have otherwise not used Loki and do not want to use Promtail how they can send logs directly to it, or at least how to get the `topology` property to pass into whatever workload is logging there.

**Comment by dstathis** [comment]
I think what I would like to do here is add a section in the docs for `LokiPushApiConsumer` that explains the labels that *the rest* of the stack uses and recommends adding them if you want continuity. I would write this in a way that would hopefully be read as a helpful suggestion and not dictating how to use the software.

**Comment by rbarry82** [comment]
Closed by #165
