### ISSUE TITLE
Loki occasionally goes into error state on removal

### ISSUE THREAD

**Issue by sed-i** [canonical/loki-k8s-operator#219]
### Bug Description

When destroying the model, loki occasionally goes into error state.
```
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "loki" (cannot start service while terminating)
```

### To Reproduce

1. deploy cos-lite bundle
2. `juju destroy-model --destroy-storage`

### Environment

```
Model  Controller  Cloud/Region        Version  SLA          Timestamp       Notes
m7     chdv2934    microk8s/localhost  2.9.34   unsupported  17:36:45-05:00  attempt 13 to destroy model failed (will retry):  model not empty, found 6 applications (model not empty)

App           Version  Status   Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager           unknown    0/1  alertmanager-k8s  edge      37  10.152.183.48   no       
catalogue              active     0/1  catalogue-k8s     edge       4  10.152.183.157  no       
grafana       9.2.1    active       1  grafana-k8s                  0  10.152.183.208  no       
loki                   unknown    0/1  loki-k8s          edge      47  10.152.183.103  no       
prometheus             unknown    0/1  prometheus-k8s               0  10.152.183.109  no       
traefik                unknown    0/1  traefik-k8s       edge      93  192.168.1.10    no  
```

### Relevant log output

```shell
unit-loki-0: 17:33:51.740 DEBUG unit.loki/0.juju-log alertmanager:11: No alertmanagers available
unit-loki-0: 17:33:51.789 INFO unit.loki/0.juju-log alertmanager:11: Pushed new configuration
unit-loki-0: 17:33:51.982 ERROR unit.loki/0.juju-log alertmanager:11: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 500, in <module>
    main(LokiOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py", line 187, in _on_relation_departed
    self.on.cluster_changed.emit()
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 157, in _on_alertmanager_change
    self._configure()
  File "./src/charm.py", line 269, in _configure
    self._container.restart(self._name)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1456, in restart
    self._pebble.restart_services(service_names)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/pebble.py", line 1699, in restart_services
    return self._services_action('restart', services, timeout, delay)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/pebble.py", line 1721, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "loki" (cannot start service while terminating)
----- Logs from task 0 -----
2022-11-22T22:33:51Z INFO Service "loki" already stopping.
----- Logs from task 1 -----
2022-11-22T22:33:51Z ERROR cannot start service while terminating
-----
unit-loki-0: 17:33:52.223 ERROR juju.worker.uniter.operation hook "alertmanager-relation-departed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by sed-i** [comment]
`can_connect` should be sufficient (rather than the not-so-pretty `except ChangeError`).

**Comment by Abuelodelanada** [comment]
@sed-i I was not able to reproduce this issue in a [Multipass VM with 3vCPU and 6Gb RAM running juju 2.9.37](https://github.com/Abuelodelanada/charm-dev-utils#charm-dev-juju-29yaml)


Anyway, reading the stack trace and the code, seems like `can_connect` is not sufficient:

![imagen](https://user-images.githubusercontent.com/939888/208113054-a86650f7-e396-4fbf-954a-3cc0e60d1d52.png)


Besides the error says:

```
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "loki" (cannot start service while terminating)
----- Logs from task 0 -----
2022-11-22T22:33:51Z INFO Service "loki" already stopping.
----- Logs from task 1 -----
2022-11-22T22:33:51Z ERROR cannot start service while terminating
```

Loki service is terminating (because we are destroying the model) and we are trying to restart it...

**Comment by sed-i** [comment]
Yep, seems like an artefact of the common exit hook. `except ChangeError` and blocked status then?

**Comment by Abuelodelanada** [comment]
Hello @benhoyt 

Sometimes while destroying the model in which loki and other related charms are running we get an: 

```
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "loki" (cannot start service while terminating)
```

As far as I understand this is because `juju destroy-model` fires a lot of events, for instance: `*-relation-departed`. In our code we observe these events to re-generate loki config and restart the service.
But since loki is being destroyed in that specific moment we get the `ChangeError`.

Despite of the fact we can solve this in our side by running the `self._container.restart(self._name)` inside a `try...except ChangeError:` the code would end up in something no so expressive.

`ChangeError` is ["raised by actions when a change is ready but has an error."](https://github.com/canonical/operator/blob/main/ops/pebble.py#L344).
Is this true in this situation? I mean, is the `restart` ready?


That's why we were wondering if there is a better way to address this kind of situations. We are using a `if not self._container.can_connect():` guard, but it is useless in this situation since we actually can connect to the container that is being destroyed.


Please let us know your thoughts! :-)

**Comment by benhoyt** [comment]
A "change" has a very specific meaning in Pebble. It's a record of a user-initiated action, and has 1 or more sub-tasks that perform the actual work (probably only 1 in this case). For a change to be "ready" simply means that it's finished -- but it may be finished in an error state, hence `pebble.py` raising the `ChangeError`.

So I think if you want to gracefully handle the model being destroyed, catching the `ChangeError` sounds like the right thing to do here.
