### ISSUE TITLE
Is it possible to improve user experience while having LogQL valid alert rules?

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-k8s-operator#229]
### Enhancement Proposal

I am starting this discussion with the intention that we all think about whether there is room for improvement in the way warning rules are written.

## Initial situation

Unlike Prometheus alert rules, when writing Loki based alert rules `%%juju_topology%%` is needed just to [be replaced afterwards with `job=".+"`](https://github.com/canonical/loki-k8s-operator/blob/main/lib/charms/loki_k8s/v0/loki_push_api.py#L768):

```python
# insert juju topology filters into a prometheus alert rule
# logql doesn't like empty matchers, so add a job matcher which hits
# any string as a "wildcard" which the topology labels will
# filter down
alert_rule["expr"] = self.tool.inject_label_matchers(
                            re.sub(r"%%juju_topology%%", r'job=".+"', alert_rule["expr"]),
                            self.topology.label_matcher_dict,
                        )
``` 

So, if we create the following alert rule file:

```yaml
alert: ErrorLevelLogsFound
expr: rate({%%juju_topology%%} |= "level=error"[1m]) > 0
for: 1m
labels:
  severity: critical
annotations:
  summary: error level logs found.
```

When the relation between Loki and the consumer charm is established, the `expr` will be modified. The first modification will replace `%%juju_topology%%` with `job=".+"`:

```
rate({job=".+"} |= "level=error"[1m]) > 0
```

After that, juju_topology is added using `cos-tool`, so the `expr` will be:

```
(rate({job=".+", juju_application="traefik", juju_charm="traefik-k8s", juju_model="cos",
      juju_model_uuid="381236d6-8c63-4415-80ad-bfdccc1ddb4c"} |= "level=error"[1m])
      > 0)
```

## Some considerations about this approach:

1. Since we need to add `%%juju_topology%%` the `expr` we are writing in the alert rule file is NOT LogQl valid:
   ```shell 
   $ ./cos-tool-amd64 --format logql transform --label-matcher juju_model=cos 'rate({%%juju_topology%%} |= "level=error"[1m]) > 0'
   FATA[0000] parse error at line 1, col 7: syntax error: unexpected %, expecting IDENTIFIER
   ```
2. From an user experience point of view, writing Loki alert rules files differs from writing Prometheus alert rules files, since in Loki `%%juju_topology%%` is mandatory. 

3. The resulting expression will have a [wildcard label matcher](https://github.com/canonical/loki-k8s-operator/issues/228) that can be avoided since we inject the juju topology.

4. Let's say we decide not to use `%%juju_topology%%` in `exp`:
   ```
   rate({} |= "level=error"[1m]) > 0
   ```
   In this situation cos-tool will fail also because logql doesn't like empty matchers in `expr`:

   ```shell
   $ ./cos-tool-amd64 --format logql transform --label-matcher juju_model=cos 'rate({} |=   "level=error"[1m]) > 0'
   FATA[0000] parse error at line 1, col 7: syntax error: unexpected }, expecting IDENTIFIER 
   ```
   And in juju debug-log you'll see:

   ```
   unit-loki-0: 11:09:02.893 WARNING unit.loki/0.logging-relation-changed   time="2023-01-06T14:09:02Z" level=fatal msg="parse error at line 1, col 7: syntax error: unexpected }, expecting IDENTIFIER"
   ```

**Comment by sed-i** [comment]
We could:
- replace `{%%juju_topology%%}` with `{job=".+"}` in all docs; or
- modify lexer in cos-tool (seems difficult); or
- in python, blindly replace `{} [|=~]` with `{job=".+"}` (ish).

**Comment by rbarry82** [comment]
This is complicated. PromQL is, ultimately, a series of individual operations which combine into a quasi-set-theory operation.

LogQL is... not. The parsing in [`cos-tool` looks pretty small](https://github.com/canonical/cos-tool/blob/main/pkg/tool/logql_transform.go#L25), and it is... except for that whole `.Walk()` thing. Because an `Expr` [is an interface](https://github.com/grafana/loki/blob/b4440911e0faa625d7d187747653d3480ef4c0a3/pkg/logql/syntax/ast.go#L21) which has one of many, many possible implementations, and it's [quite literally tokenized and lexed](https://github.com/canonical/cos-tool/blob/e5cf0be302da04a24e429da819293b5b09ebb473/pkg/logql/syntax/lex.go), because a sample, pipeline, colorizer, and every other type may be its own thing.

This code is shockingly complex. It's all interfaces, so we _could_ make our own implementation, but... there's no way it won't be brittle, and almost all of the actual functions are not exported in any case, so we'd need to edit it and change the visibility everywhere, or gamble on a re-implementation.

If we had a complete (or even partial) list of operations where we *knew* a selector was required, a regexp from Python to insert it if it's not present (across multiple places in the complete expression if necessary) would honestly be easy enough. Even from the LogQL examples, though, it's not good enough to just look for empty `()` or even `(\{(\[\])?\})`, because:

```
sum by(machine) (count_over_time({app="foo"}[1m])) / on() sum(count_over_time({app="foo"}[1m]))
```

In that example, it would (erroneously) try to add one to `by(machine)`, `on()`, etc. If we do this at all, it should be from Python, but it may not be a solvable problem.
