### ISSUE TITLE
Warn the user multiple standalone units.

### ISSUE THREAD

**Issue by dstathis** [canonical/loki-k8s-operator#80]
If the juju admin scales up loki without proper HA support, we need to supply sufficient warnings. Log messages and possibly status messages should explain the issues with doing it this way and make it clear that it is not supported.

**Comment by mmanciop** [comment]
For context, this is needed inly with Loki charmed in “standalone” mode, in which multiple units are effectively entirely independent Loki setups. That is most likely not the intent of a Juju administrator, and we need to signal it visibly with WARNINGs in logs and unit statuses.

**Comment by balbirthomas** [comment]
Addressing this issue would require adding a peer relation in the Loki charm, in order to detect peer relation joined events and set appropriate warning messages. An alternative would be to check `self.app.planned_units()` in say the constructor or some other event handler like update status and set the warning message. The former will certainly work the later approach needs validation and is an odd solution hence the plan is to use the former approach.

**Comment by mmanciop** [comment]
Outdated issue. We have now a design for the loki_push_api relation that will work just fine with standalone loki units and the usecase of multiple standalone units should be fully supported, so no need of warning anybody.

**Comment by mmanciop** [comment]
Also, @balbirthomas, there is no need for the peer relation to fulfill this usecase. During the pebble_ready event hook the logic could check whether more than one unit of the charm is planned, and then log.
